news:
  sites:
    - name: "JOONGANG"
      base-url: "https://www.joongang.co.kr/world/"
      continent-url:
        AM: "northame"
        CN: "china"
        JP: "japan"
        EU: "eu"
      article-xpath: "//ul[@class='story_list']//li[@class='card']"
      url-xpath: ".//div[@class='card_body']//h2//a"
      title-xpath: ".//div[@class='card_body']//h2//a"
      content-xpath: ".//p[@class='description']"
      date-xpath: ".//p[@class='date']"
      img-xpath: ".//figure[@class='card_image']//img"
      page-param: "page"
      date-separator: "."

    - name: "HANI"
      base-url: "https://www.hani.co.kr/"
      continent-url:
        AS: "arti/international/asiapacific"
        AM: "arti/international/america"
        AF: "arti/international/arabafrica"
        CN: "arti/international/china"
        JP: "arti/international/japan"
        EU: "arti/international/europe"
        KR: "arti/area/area_general"
      article-xpath: "//li[@class='ArticleList_item___OGQO']"
      url-xpath: ".//a[@class='BaseArticleCard_link__Q3YFK']"
      title-xpath: ".//div[@class='title BaseArticleCard_title__TVFqt']"
      content-xpath: ".//p[@class='BaseArticleCard_prologue__vToX3']"
      date-xpath: ".//div[@class='BaseArticleCard_date__4R8Ru']"
      img-xpath: ".//img"
      page-param: "page"
      date-separator: "-"

    - name: "HANKYUNG"
      base-url: "https://www.hankyung.com/"
      continent-url:
        AS: "international/0901-0902"
        AM: "international/0903-0904"
        AF: "international/0906-0906"
        EU: "international/0905"
      article-xpath: "//div[@class='news-item']"
      url-xpath: ".//h2[@class='news-tit']//a"
      title-xpath: ".//h2[@class='news-tit']//a"
      content-xpath: ".//p[@class='lead']"
      date-xpath: ".//p[@class='txt-date']"
      img-xpath: ".//img"
      page-param: "page"
      date-separator: "."

    - name: "HANKOOK"
      base-url: "https://www.hankookilbo.com/"
      continent-url:
        AS: "News/World/HD01"
        AM: "News/World/HD02"
        AF: "News/World/HD04"
        EU: "News/World/HD03"
      article-xpath: "//ul[@class='board-list column-3']//li"
      url-xpath: ".//div[@class='text-box']//h3//a"
      title-xpath: ".//div[@class='text-box']//h3//a"
      content-xpath: ".//div[@class='text']//a"
      date-xpath: ".//span[@class='date']"
      img-xpath: ".//img"
      page-param: "Page"
      date-separator: "."

    - name: "SEGYE"
      base-url: "https://www.segye.com/"
      continent-url:
        AS: "newsList/0101040500000"
        AM: "newsList/0101040200000"
        AF: "newsList/0101040700000"
        CN: "newsList/0101040300000"
        JP: "newsList/0101040400000"
        EU: "newsList/0101040600000"
        KR: "newsList/0101070000000"
      article-xpath: "//ul[@class='listBox']//li"
      url-xpath: ".//a"
      title-xpath: ".//strong[@class='tit']"
      content-xpath: ".//span[@class='cont']"
      date-xpath: ".//small[@class='date']"
      img-xpath: ".//img"
      page-param: "page"
      date-separator: "-"
